# Generated by Django 3.2.7 on 2021-09-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudios',
            options={'verbose_name': 'Estudio'},
        ),
    ]
