# Generated by Django 3.2.7 on 2021-09-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='fecha_fin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
