# Generated by Django 3.2.7 on 2021-09-30 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estudios', '0002_alter_estudios_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to=settings.AUTH_USER_MODEL),
        ),
    ]
