version: '3.9'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"] #Buena práctica, ahorra tiempo/recursos
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - dbxd #se llama igual que abajo

  dbxd: #debe llamarse igual que en las variables de entorno - .env.template
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data #Ésto lo manejará docker

volumes:
  postgres_data:

